{
  "health_status": {
    "overall_status": "unhealthy",
    "services": {
      "duri_core": {
        "status": "healthy",
        "response_time": 0.00165,
        "last_check": "2025-07-28T10:35:36.608151",
        "uptime": 1.013832
      },
      "duri_brain": {
        "status": "unhealthy",
        "error": "HTTPConnectionPool(host='localhost', port=8081): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3035629db0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "last_check": "2025-07-28T10:35:36.608718"
      },
      "duri_evolution": {
        "status": "healthy",
        "response_time": 0.001656,
        "last_check": "2025-07-28T10:35:36.610639",
        "uptime": 1.016318
      },
      "duri_control": {
        "status": "healthy",
        "response_time": 0.001096,
        "last_check": "2025-07-28T10:35:36.611990",
        "uptime": 1.01767
      }
    },
    "timestamp": "2025-07-28T10:35:36.612079",
    "uptime": 1.017757
  },
  "system_metrics": {
    "memory_usage_percent": 13.8,
    "memory_available_mb": 13704.140625,
    "cpu_percent": 0.4,
    "disk_usage_percent": 1.5
  },
  "report_generated": "2025-07-28T10:35:37.612843"
}
